version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "subosito/*"
          - "softprops/*"

  - package-ecosystem: "pub"
    directory: "/music_hub"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
