// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/ast.dart';
import 'api/cleanup.dart';
import 'api/database.dart';
import 'api/duplicates.dart';
import 'api/fingerprint.dart';
import 'api/lyrics.dart';
import 'api/metadata.dart';
import 'api/renamer.dart';
import 'api/simple.dart';
import 'api/snapshots.dart';
import 'api/spectral.dart';
import 'api/sync.dart';
import 'api/transcode.dart';
import 'api/watcher.dart';
import 'api/windows_devices.dart';
import 'api/windows_shell.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ResultAudioMetadataStringPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ResultAudioMetadataString
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          dynamic raw);

  @protected
  ResultAudioMetadataString
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AcousticFingerprint dco_decode_acoustic_fingerprint(dynamic raw);

  @protected
  AudioMetadata dco_decode_audio_metadata(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AudioMetadata dco_decode_box_autoadd_audio_metadata(dynamic raw);

  @protected
  DbTrack dco_decode_box_autoadd_db_track(dynamic raw);

  @protected
  Expr dco_decode_box_autoadd_expr(dynamic raw);

  @protected
  LearningRule dco_decode_box_autoadd_learning_rule(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Expr dco_decode_box_expr(dynamic raw);

  @protected
  DbTrack dco_decode_db_track(dynamic raw);

  @protected
  Expr dco_decode_expr(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LearningRule dco_decode_learning_rule(dynamic raw);

  @protected
  List<ResultAudioMetadataString>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DbTrack> dco_decode_list_db_track(dynamic raw);

  @protected
  List<LearningRule> dco_decode_list_learning_rule(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  Rule dco_decode_rule(dynamic raw);

  @protected
  SpectralAnalysisResult dco_decode_spectral_analysis_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ResultAudioMetadataString
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          SseDeserializer deserializer);

  @protected
  ResultAudioMetadataString
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AcousticFingerprint sse_decode_acoustic_fingerprint(
      SseDeserializer deserializer);

  @protected
  AudioMetadata sse_decode_audio_metadata(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AudioMetadata sse_decode_box_autoadd_audio_metadata(
      SseDeserializer deserializer);

  @protected
  DbTrack sse_decode_box_autoadd_db_track(SseDeserializer deserializer);

  @protected
  Expr sse_decode_box_autoadd_expr(SseDeserializer deserializer);

  @protected
  LearningRule sse_decode_box_autoadd_learning_rule(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Expr sse_decode_box_expr(SseDeserializer deserializer);

  @protected
  DbTrack sse_decode_db_track(SseDeserializer deserializer);

  @protected
  Expr sse_decode_expr(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LearningRule sse_decode_learning_rule(SseDeserializer deserializer);

  @protected
  List<ResultAudioMetadataString>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DbTrack> sse_decode_list_db_track(SseDeserializer deserializer);

  @protected
  List<LearningRule> sse_decode_list_learning_rule(
      SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Rule sse_decode_rule(SseDeserializer deserializer);

  @protected
  SpectralAnalysisResult sse_decode_spectral_analysis_result(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          ResultAudioMetadataString self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          ResultAudioMetadataString self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_acoustic_fingerprint(
      AcousticFingerprint self, SseSerializer serializer);

  @protected
  void sse_encode_audio_metadata(AudioMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_audio_metadata(
      AudioMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_db_track(DbTrack self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_expr(Expr self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_learning_rule(
      LearningRule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_expr(Expr self, SseSerializer serializer);

  @protected
  void sse_encode_db_track(DbTrack self, SseSerializer serializer);

  @protected
  void sse_encode_expr(Expr self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_learning_rule(LearningRule self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          List<ResultAudioMetadataString> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_db_track(List<DbTrack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_learning_rule(
      List<LearningRule> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_rule(Rule self, SseSerializer serializer);

  @protected
  void sse_encode_spectral_analysis_result(
      SpectralAnalysisResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          int ptr);
}
