// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ast.dart';
import 'api/cleanup.dart';
import 'api/database.dart';
import 'api/duplicates.dart';
import 'api/fingerprint.dart';
import 'api/lyrics.dart';
import 'api/metadata.dart';
import 'api/renamer.dart';
import 'api/simple.dart';
import 'api/snapshots.dart';
import 'api/spectral.dart';
import 'api/sync.dart';
import 'api/transcode.dart';
import 'api/watcher.dart';
import 'api/windows_devices.dart';
import 'api/windows_shell.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 937372604;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_music_tag_editor',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<SpectralAnalysisResult> crateApiSpectralAnalyzeSpectralQuality(
      {required String path});

  Future<String> crateApiCleanupCleanTag({required String text});

  Future<String> crateApiTranscodeConvertToWav(
      {required String inputPath, required String outputPath});

  Future<void> crateApiSnapshotsCreateMetadataSnapshot(
      {required String dbPath,
      required String filePath,
      required String metadataJson});

  Future<String> crateApiDuplicatesDiagnoseFile({required String path});

  Future<void> crateApiLyricsEmbedLyricsToFile(
      {required String path, required String lyrics});

  Future<String> crateApiAstEvaluateAst(
      {required Expr expr, required AudioMetadata metadata});

  Future<String> crateApiAstEvaluateRule(
      {required String rule, required AudioMetadata metadata});

  Future<String> crateApiRenamerExecuteRenameBatch(
      {required String jsonPreviews});

  Future<Uint8List?> crateApiMetadataExtractAndOptimizeCover(
      {required String path, required int maxSize});

  Future<Uint8List?> crateApiMetadataExtractCoverArt({required String path});

  Future<String> crateApiDuplicatesGenerateAcousticFingerprint(
      {required String path});

  Future<AcousticFingerprint> crateApiFingerprintGenerateFingerprint(
      {required String path});

  Future<List<DbTrack>> crateApiDatabaseGetAllTracks({required String dbPath});

  Future<String> crateApiTranscodeGetAudioDetails({required String path});

  Future<List<String>> crateApiSnapshotsGetFileHistory(
      {required String dbPath, required String filePath});

  Future<List<LearningRule>> crateApiDatabaseGetLearningRules(
      {required String dbPath});

  Future<String> crateApiRenamerGetRenamePreview(
      {required List<String> paths, required String rule});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiDatabaseInitDb({required String dbPath});

  Future<List<String>> crateApiWindowsDevicesListConnectedMobileDevices();

  Future<void> crateApiWindowsDevicesOpenMobileFolderInExplorer(
      {required String deviceName});

  Future<Expr> crateApiAstParseToAst({required String input});

  Future<String> crateApiWindowsDevicesPushToMobileDevice(
      {required String localPath, required String deviceName});

  Future<AudioMetadata> crateApiMetadataReadMetadata({required String path});

  Future<List<ResultAudioMetadataString>> crateApiMetadataReadMetadataBatch(
      {required List<String> paths});

  Future<String> crateApiWindowsShellRegisterShellExtension(
      {required String exePath});

  Future<String> crateApiDuplicatesRepairFileHeader({required String path});

  Future<void> crateApiAstRuleAllRules();

  Future<void> crateApiDatabaseSaveLearningRule(
      {required String dbPath, required LearningRule rule});

  Future<void> crateApiDatabaseSaveTrack(
      {required String dbPath, required DbTrack track});

  Future<String> crateApiLyricsSearchLyrics(
      {required String artist, required String title});

  Future<List<DbTrack>> crateApiDatabaseSearchTracks(
      {required String dbPath, required String query});

  Stream<String> crateApiWatcherStartWatcher({required String folderPath});

  Future<String> crateApiSyncSyncTagsAcrossFormats(
      {required String masterPath, required List<String> otherPaths});

  Future<String> crateApiWindowsShellUnregisterShellExtension();

  Future<void> crateApiMetadataWriteMetadata(
      {required String path, required AudioMetadata metadata});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ResultAudioMetadataString;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ResultAudioMetadataString;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ResultAudioMetadataStringPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SpectralAnalysisResult> crateApiSpectralAnalyzeSpectralQuality(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_spectral_analysis_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSpectralAnalyzeSpectralQualityConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpectralAnalyzeSpectralQualityConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_spectral_quality",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiCleanupCleanTag({required String text}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCleanupCleanTagConstMeta,
      argValues: [text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCleanupCleanTagConstMeta => const TaskConstMeta(
        debugName: "clean_tag",
        argNames: ["text"],
      );

  @override
  Future<String> crateApiTranscodeConvertToWav(
      {required String inputPath, required String outputPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inputPath, serializer);
        sse_encode_String(outputPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTranscodeConvertToWavConstMeta,
      argValues: [inputPath, outputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTranscodeConvertToWavConstMeta =>
      const TaskConstMeta(
        debugName: "convert_to_wav",
        argNames: ["inputPath", "outputPath"],
      );

  @override
  Future<void> crateApiSnapshotsCreateMetadataSnapshot(
      {required String dbPath,
      required String filePath,
      required String metadataJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(filePath, serializer);
        sse_encode_String(metadataJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSnapshotsCreateMetadataSnapshotConstMeta,
      argValues: [dbPath, filePath, metadataJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSnapshotsCreateMetadataSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "create_metadata_snapshot",
        argNames: ["dbPath", "filePath", "metadataJson"],
      );

  @override
  Future<String> crateApiDuplicatesDiagnoseFile({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDuplicatesDiagnoseFileConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDuplicatesDiagnoseFileConstMeta =>
      const TaskConstMeta(
        debugName: "diagnose_file",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiLyricsEmbedLyricsToFile(
      {required String path, required String lyrics}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(lyrics, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLyricsEmbedLyricsToFileConstMeta,
      argValues: [path, lyrics],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLyricsEmbedLyricsToFileConstMeta =>
      const TaskConstMeta(
        debugName: "embed_lyrics_to_file",
        argNames: ["path", "lyrics"],
      );

  @override
  Future<String> crateApiAstEvaluateAst(
      {required Expr expr, required AudioMetadata metadata}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_expr(expr, serializer);
        sse_encode_box_autoadd_audio_metadata(metadata, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAstEvaluateAstConstMeta,
      argValues: [expr, metadata],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAstEvaluateAstConstMeta => const TaskConstMeta(
        debugName: "evaluate_ast",
        argNames: ["expr", "metadata"],
      );

  @override
  Future<String> crateApiAstEvaluateRule(
      {required String rule, required AudioMetadata metadata}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(rule, serializer);
        sse_encode_box_autoadd_audio_metadata(metadata, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAstEvaluateRuleConstMeta,
      argValues: [rule, metadata],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAstEvaluateRuleConstMeta => const TaskConstMeta(
        debugName: "evaluate_rule",
        argNames: ["rule", "metadata"],
      );

  @override
  Future<String> crateApiRenamerExecuteRenameBatch(
      {required String jsonPreviews}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(jsonPreviews, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRenamerExecuteRenameBatchConstMeta,
      argValues: [jsonPreviews],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRenamerExecuteRenameBatchConstMeta =>
      const TaskConstMeta(
        debugName: "execute_rename_batch",
        argNames: ["jsonPreviews"],
      );

  @override
  Future<Uint8List?> crateApiMetadataExtractAndOptimizeCover(
      {required String path, required int maxSize}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_32(maxSize, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMetadataExtractAndOptimizeCoverConstMeta,
      argValues: [path, maxSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetadataExtractAndOptimizeCoverConstMeta =>
      const TaskConstMeta(
        debugName: "extract_and_optimize_cover",
        argNames: ["path", "maxSize"],
      );

  @override
  Future<Uint8List?> crateApiMetadataExtractCoverArt({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMetadataExtractCoverArtConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetadataExtractCoverArtConstMeta =>
      const TaskConstMeta(
        debugName: "extract_cover_art",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiDuplicatesGenerateAcousticFingerprint(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDuplicatesGenerateAcousticFingerprintConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDuplicatesGenerateAcousticFingerprintConstMeta =>
      const TaskConstMeta(
        debugName: "generate_acoustic_fingerprint",
        argNames: ["path"],
      );

  @override
  Future<AcousticFingerprint> crateApiFingerprintGenerateFingerprint(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_acoustic_fingerprint,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFingerprintGenerateFingerprintConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFingerprintGenerateFingerprintConstMeta =>
      const TaskConstMeta(
        debugName: "generate_fingerprint",
        argNames: ["path"],
      );

  @override
  Future<List<DbTrack>> crateApiDatabaseGetAllTracks({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_db_track,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDatabaseGetAllTracksConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatabaseGetAllTracksConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_tracks",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiTranscodeGetAudioDetails({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTranscodeGetAudioDetailsConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTranscodeGetAudioDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "get_audio_details",
        argNames: ["path"],
      );

  @override
  Future<List<String>> crateApiSnapshotsGetFileHistory(
      {required String dbPath, required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSnapshotsGetFileHistoryConstMeta,
      argValues: [dbPath, filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSnapshotsGetFileHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "get_file_history",
        argNames: ["dbPath", "filePath"],
      );

  @override
  Future<List<LearningRule>> crateApiDatabaseGetLearningRules(
      {required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_learning_rule,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDatabaseGetLearningRulesConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatabaseGetLearningRulesConstMeta =>
      const TaskConstMeta(
        debugName: "get_learning_rules",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiRenamerGetRenamePreview(
      {required List<String> paths, required String rule}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(paths, serializer);
        sse_encode_String(rule, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiRenamerGetRenamePreviewConstMeta,
      argValues: [paths, rule],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRenamerGetRenamePreviewConstMeta =>
      const TaskConstMeta(
        debugName: "get_rename_preview",
        argNames: ["paths", "rule"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiDatabaseInitDb({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDatabaseInitDbConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatabaseInitDbConstMeta => const TaskConstMeta(
        debugName: "init_db",
        argNames: ["dbPath"],
      );

  @override
  Future<List<String>> crateApiWindowsDevicesListConnectedMobileDevices() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWindowsDevicesListConnectedMobileDevicesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWindowsDevicesListConnectedMobileDevicesConstMeta =>
          const TaskConstMeta(
            debugName: "list_connected_mobile_devices",
            argNames: [],
          );

  @override
  Future<void> crateApiWindowsDevicesOpenMobileFolderInExplorer(
      {required String deviceName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(deviceName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsDevicesOpenMobileFolderInExplorerConstMeta,
      argValues: [deviceName],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWindowsDevicesOpenMobileFolderInExplorerConstMeta =>
          const TaskConstMeta(
            debugName: "open_mobile_folder_in_explorer",
            argNames: ["deviceName"],
          );

  @override
  Future<Expr> crateApiAstParseToAst({required String input}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(input, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_expr,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAstParseToAstConstMeta,
      argValues: [input],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAstParseToAstConstMeta => const TaskConstMeta(
        debugName: "parse_to_ast",
        argNames: ["input"],
      );

  @override
  Future<String> crateApiWindowsDevicesPushToMobileDevice(
      {required String localPath, required String deviceName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(localPath, serializer);
        sse_encode_String(deviceName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsDevicesPushToMobileDeviceConstMeta,
      argValues: [localPath, deviceName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWindowsDevicesPushToMobileDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "push_to_mobile_device",
        argNames: ["localPath", "deviceName"],
      );

  @override
  Future<AudioMetadata> crateApiMetadataReadMetadata({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_audio_metadata,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMetadataReadMetadataConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetadataReadMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "read_metadata",
        argNames: ["path"],
      );

  @override
  Future<List<ResultAudioMetadataString>> crateApiMetadataReadMetadataBatch(
      {required List<String> paths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(paths, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMetadataReadMetadataBatchConstMeta,
      argValues: [paths],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetadataReadMetadataBatchConstMeta =>
      const TaskConstMeta(
        debugName: "read_metadata_batch",
        argNames: ["paths"],
      );

  @override
  Future<String> crateApiWindowsShellRegisterShellExtension(
      {required String exePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(exePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsShellRegisterShellExtensionConstMeta,
      argValues: [exePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWindowsShellRegisterShellExtensionConstMeta =>
      const TaskConstMeta(
        debugName: "register_shell_extension",
        argNames: ["exePath"],
      );

  @override
  Future<String> crateApiDuplicatesRepairFileHeader({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDuplicatesRepairFileHeaderConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDuplicatesRepairFileHeaderConstMeta =>
      const TaskConstMeta(
        debugName: "repair_file_header",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiAstRuleAllRules() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAstRuleAllRulesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAstRuleAllRulesConstMeta => const TaskConstMeta(
        debugName: "rule_all_rules",
        argNames: [],
      );

  @override
  Future<void> crateApiDatabaseSaveLearningRule(
      {required String dbPath, required LearningRule rule}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_box_autoadd_learning_rule(rule, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDatabaseSaveLearningRuleConstMeta,
      argValues: [dbPath, rule],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatabaseSaveLearningRuleConstMeta =>
      const TaskConstMeta(
        debugName: "save_learning_rule",
        argNames: ["dbPath", "rule"],
      );

  @override
  Future<void> crateApiDatabaseSaveTrack(
      {required String dbPath, required DbTrack track}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_box_autoadd_db_track(track, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDatabaseSaveTrackConstMeta,
      argValues: [dbPath, track],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatabaseSaveTrackConstMeta => const TaskConstMeta(
        debugName: "save_track",
        argNames: ["dbPath", "track"],
      );

  @override
  Future<String> crateApiLyricsSearchLyrics(
      {required String artist, required String title}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(artist, serializer);
        sse_encode_String(title, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLyricsSearchLyricsConstMeta,
      argValues: [artist, title],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLyricsSearchLyricsConstMeta => const TaskConstMeta(
        debugName: "search_lyrics",
        argNames: ["artist", "title"],
      );

  @override
  Future<List<DbTrack>> crateApiDatabaseSearchTracks(
      {required String dbPath, required String query}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(query, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_db_track,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDatabaseSearchTracksConstMeta,
      argValues: [dbPath, query],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatabaseSearchTracksConstMeta =>
      const TaskConstMeta(
        debugName: "search_tracks",
        argNames: ["dbPath", "query"],
      );

  @override
  Stream<String> crateApiWatcherStartWatcher({required String folderPath}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(folderPath, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWatcherStartWatcherConstMeta,
      argValues: [folderPath, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWatcherStartWatcherConstMeta =>
      const TaskConstMeta(
        debugName: "start_watcher",
        argNames: ["folderPath", "sink"],
      );

  @override
  Future<String> crateApiSyncSyncTagsAcrossFormats(
      {required String masterPath, required List<String> otherPaths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(masterPath, serializer);
        sse_encode_list_String(otherPaths, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSyncSyncTagsAcrossFormatsConstMeta,
      argValues: [masterPath, otherPaths],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncSyncTagsAcrossFormatsConstMeta =>
      const TaskConstMeta(
        debugName: "sync_tags_across_formats",
        argNames: ["masterPath", "otherPaths"],
      );

  @override
  Future<String> crateApiWindowsShellUnregisterShellExtension() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsShellUnregisterShellExtensionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWindowsShellUnregisterShellExtensionConstMeta =>
      const TaskConstMeta(
        debugName: "unregister_shell_extension",
        argNames: [],
      );

  @override
  Future<void> crateApiMetadataWriteMetadata(
      {required String path, required AudioMetadata metadata}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_box_autoadd_audio_metadata(metadata, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 38, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMetadataWriteMetadataConstMeta,
      argValues: [path, metadata],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetadataWriteMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "write_metadata",
        argNames: ["path", "metadata"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ResultAudioMetadataString => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ResultAudioMetadataString => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ResultAudioMetadataString
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ResultAudioMetadataStringImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  ResultAudioMetadataString
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ResultAudioMetadataStringImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AcousticFingerprint dco_decode_acoustic_fingerprint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AcousticFingerprint(
      hash: dco_decode_String(arr[0]),
      durationSeconds: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  AudioMetadata dco_decode_audio_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return AudioMetadata(
      title: dco_decode_opt_String(arr[0]),
      artist: dco_decode_opt_String(arr[1]),
      album: dco_decode_opt_String(arr[2]),
      year: dco_decode_opt_box_autoadd_u_32(arr[3]),
      trackNumber: dco_decode_opt_box_autoadd_u_32(arr[4]),
      genre: dco_decode_opt_String(arr[5]),
      durationMs: dco_decode_u_32(arr[6]),
      filePath: dco_decode_String(arr[7]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AudioMetadata dco_decode_box_autoadd_audio_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_audio_metadata(raw);
  }

  @protected
  DbTrack dco_decode_box_autoadd_db_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_db_track(raw);
  }

  @protected
  Expr dco_decode_box_autoadd_expr(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_expr(raw);
  }

  @protected
  LearningRule dco_decode_box_autoadd_learning_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_learning_rule(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Expr dco_decode_box_expr(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_expr(raw);
  }

  @protected
  DbTrack dco_decode_db_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DbTrack(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      album: dco_decode_opt_String(arr[3]),
      localPath: dco_decode_String(arr[4]),
    );
  }

  @protected
  Expr dco_decode_expr(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Expr_Literal(
          dco_decode_String(raw[1]),
        );
      case 1:
        return Expr_Placeholder(
          dco_decode_String(raw[1]),
        );
      case 2:
        return Expr_Binary(
          left: dco_decode_box_expr(raw[1]),
          op: dco_decode_String(raw[2]),
          right: dco_decode_box_expr(raw[3]),
        );
      case 3:
        return Expr_If(
          cond: dco_decode_box_expr(raw[1]),
          thenBranch: dco_decode_box_expr(raw[2]),
          elseBranch: dco_decode_box_expr(raw[3]),
        );
      case 4:
        return Expr_FunctionCall(
          name: dco_decode_String(raw[1]),
          arg: dco_decode_box_expr(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LearningRule dco_decode_learning_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LearningRule(
      artist: dco_decode_opt_String(arr[0]),
      field: dco_decode_String(arr[1]),
      originalValue: dco_decode_String(arr[2]),
      correctedValue: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<ResultAudioMetadataString>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
            dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString)
        .toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DbTrack> dco_decode_list_db_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_db_track).toList();
  }

  @protected
  List<LearningRule> dco_decode_list_learning_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_learning_rule).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  Rule dco_decode_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Rule.values[raw as int];
  }

  @protected
  SpectralAnalysisResult dco_decode_spectral_analysis_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SpectralAnalysisResult(
      qualityStatus: dco_decode_String(arr[0]),
      isFakeHighRes: dco_decode_bool(arr[1]),
      frequencyMagnitudes: dco_decode_list_prim_f_32_strict(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ResultAudioMetadataString
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ResultAudioMetadataStringImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ResultAudioMetadataString
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ResultAudioMetadataStringImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AcousticFingerprint sse_decode_acoustic_fingerprint(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hash = sse_decode_String(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    return AcousticFingerprint(
        hash: var_hash, durationSeconds: var_durationSeconds);
  }

  @protected
  AudioMetadata sse_decode_audio_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_trackNumber = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_genre = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_u_32(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    return AudioMetadata(
        title: var_title,
        artist: var_artist,
        album: var_album,
        year: var_year,
        trackNumber: var_trackNumber,
        genre: var_genre,
        durationMs: var_durationMs,
        filePath: var_filePath);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AudioMetadata sse_decode_box_autoadd_audio_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_audio_metadata(deserializer));
  }

  @protected
  DbTrack sse_decode_box_autoadd_db_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_db_track(deserializer));
  }

  @protected
  Expr sse_decode_box_autoadd_expr(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_expr(deserializer));
  }

  @protected
  LearningRule sse_decode_box_autoadd_learning_rule(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_learning_rule(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  Expr sse_decode_box_expr(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_expr(deserializer));
  }

  @protected
  DbTrack sse_decode_db_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_localPath = sse_decode_String(deserializer);
    return DbTrack(
        id: var_id,
        title: var_title,
        artist: var_artist,
        album: var_album,
        localPath: var_localPath);
  }

  @protected
  Expr sse_decode_expr(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return Expr_Literal(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return Expr_Placeholder(var_field0);
      case 2:
        var var_left = sse_decode_box_expr(deserializer);
        var var_op = sse_decode_String(deserializer);
        var var_right = sse_decode_box_expr(deserializer);
        return Expr_Binary(left: var_left, op: var_op, right: var_right);
      case 3:
        var var_cond = sse_decode_box_expr(deserializer);
        var var_thenBranch = sse_decode_box_expr(deserializer);
        var var_elseBranch = sse_decode_box_expr(deserializer);
        return Expr_If(
            cond: var_cond,
            thenBranch: var_thenBranch,
            elseBranch: var_elseBranch);
      case 4:
        var var_name = sse_decode_String(deserializer);
        var var_arg = sse_decode_box_expr(deserializer);
        return Expr_FunctionCall(name: var_name, arg: var_arg);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LearningRule sse_decode_learning_rule(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_artist = sse_decode_opt_String(deserializer);
    var var_field = sse_decode_String(deserializer);
    var var_originalValue = sse_decode_String(deserializer);
    var var_correctedValue = sse_decode_String(deserializer);
    return LearningRule(
        artist: var_artist,
        field: var_field,
        originalValue: var_originalValue,
        correctedValue: var_correctedValue);
  }

  @protected
  List<ResultAudioMetadataString>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ResultAudioMetadataString>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
          sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
              deserializer));
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DbTrack> sse_decode_list_db_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DbTrack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_db_track(deserializer));
    }
    return ans_;
  }

  @protected
  List<LearningRule> sse_decode_list_learning_rule(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LearningRule>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_learning_rule(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Rule sse_decode_rule(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Rule.values[inner];
  }

  @protected
  SpectralAnalysisResult sse_decode_spectral_analysis_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_qualityStatus = sse_decode_String(deserializer);
    var var_isFakeHighRes = sse_decode_bool(deserializer);
    var var_frequencyMagnitudes =
        sse_decode_list_prim_f_32_strict(deserializer);
    return SpectralAnalysisResult(
        qualityStatus: var_qualityStatus,
        isFakeHighRes: var_isFakeHighRes,
        frequencyMagnitudes: var_frequencyMagnitudes);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          ResultAudioMetadataString self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ResultAudioMetadataStringImpl)
            .frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          ResultAudioMetadataString self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ResultAudioMetadataStringImpl)
            .frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_acoustic_fingerprint(
      AcousticFingerprint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hash, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
  }

  @protected
  void sse_encode_audio_metadata(AudioMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackNumber, serializer);
    sse_encode_opt_String(self.genre, serializer);
    sse_encode_u_32(self.durationMs, serializer);
    sse_encode_String(self.filePath, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_audio_metadata(
      AudioMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_audio_metadata(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_db_track(DbTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_db_track(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_expr(Expr self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_expr(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_learning_rule(
      LearningRule self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_learning_rule(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_expr(Expr self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_expr(self, serializer);
  }

  @protected
  void sse_encode_db_track(DbTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_String(self.localPath, serializer);
  }

  @protected
  void sse_encode_expr(Expr self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Expr_Literal(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case Expr_Placeholder(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case Expr_Binary(left: final left, op: final op, right: final right):
        sse_encode_i_32(2, serializer);
        sse_encode_box_expr(left, serializer);
        sse_encode_String(op, serializer);
        sse_encode_box_expr(right, serializer);
      case Expr_If(
          cond: final cond,
          thenBranch: final thenBranch,
          elseBranch: final elseBranch
        ):
        sse_encode_i_32(3, serializer);
        sse_encode_box_expr(cond, serializer);
        sse_encode_box_expr(thenBranch, serializer);
        sse_encode_box_expr(elseBranch, serializer);
      case Expr_FunctionCall(name: final name, arg: final arg):
        sse_encode_i_32(4, serializer);
        sse_encode_String(name, serializer);
        sse_encode_box_expr(arg, serializer);
    }
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_learning_rule(LearningRule self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_String(self.field, serializer);
    sse_encode_String(self.originalValue, serializer);
    sse_encode_String(self.correctedValue, serializer);
  }

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          List<ResultAudioMetadataString> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
          item, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_db_track(List<DbTrack> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_db_track(item, serializer);
    }
  }

  @protected
  void sse_encode_list_learning_rule(
      List<LearningRule> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_learning_rule(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_rule(Rule self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_spectral_analysis_result(
      SpectralAnalysisResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.qualityStatus, serializer);
    sse_encode_bool(self.isFakeHighRes, serializer);
    sse_encode_list_prim_f_32_strict(self.frequencyMagnitudes, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ResultAudioMetadataStringImpl extends RustOpaque
    implements ResultAudioMetadataString {
  // Not to be used by end users
  ResultAudioMetadataStringImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ResultAudioMetadataStringImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_ResultAudioMetadataString,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_ResultAudioMetadataString,
    rustArcDecrementStrongCountPtr: RustLib.instance.api
        .rust_arc_decrement_strong_count_ResultAudioMetadataStringPtr,
  );
}
