// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'metadata.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ast.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RuleParser`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `cmp`, `eq`, `fmt`, `fmt`, `hash`, `parse`, `partial_cmp`

/// Converte uma string de regra em uma AST real.
Future<Expr> parseToAst({required String input}) =>
    RustLib.instance.api.crateApiAstParseToAst(input: input);

/// Avalia a AST contra metadados.
Future<String> evaluateAst(
        {required Expr expr, required AudioMetadata metadata}) =>
    RustLib.instance.api.crateApiAstEvaluateAst(expr: expr, metadata: metadata);

/// FUNÇÃO PRINCIPAL: Avalia uma regra de texto diretamente.
/// Esta função é o que o Flutter chama, evitando a necessidade de tipos complexos no Dart.
Future<String> evaluateRule(
        {required String rule, required AudioMetadata metadata}) =>
    RustLib.instance.api
        .crateApiAstEvaluateRule(rule: rule, metadata: metadata);

@freezed
sealed class Expr with _$Expr {
  const Expr._();

  const factory Expr.literal(
    String field0,
  ) = Expr_Literal;
  const factory Expr.placeholder(
    String field0,
  ) = Expr_Placeholder;
  const factory Expr.binary({
    required Expr left,
    required String op,
    required Expr right,
  }) = Expr_Binary;
  const factory Expr.if_({
    required Expr cond,
    required Expr thenBranch,
    required Expr elseBranch,
  }) = Expr_If;
}

enum Rule {
  whitespace,

  ///Expressão principal do motor
  expression,

  ///Unidades básicas
  primary,

  ///Placeholders de metadados (ex: %artist%)
  placeholder,

  ///Identificadores (nomes de campos)
  identifier,

  ///Strings entre aspas simples
  stringLiteral,

  ///Operações binárias (+ para concatenação, == para comparação)
  binaryExpr,

  ///Operadores suportados
  operator_,

  ///Lógica condicional
  ifExpr,
  ;

  static Future<void> allRules() =>
      RustLib.instance.api.crateApiAstRuleAllRules();
}
