// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Inicializa o banco de dados com todas as tabelas necessárias e FTS5.
Future<void> initDb({required String dbPath}) =>
    RustLib.instance.api.crateApiDatabaseInitDb(dbPath: dbPath);

Future<List<DbTrack>> searchTracks(
        {required String dbPath, required String query}) =>
    RustLib.instance.api
        .crateApiDatabaseSearchTracks(dbPath: dbPath, query: query);

Future<void> saveTrack({required String dbPath, required DbTrack track}) =>
    RustLib.instance.api
        .crateApiDatabaseSaveTrack(dbPath: dbPath, track: track);

Future<List<DbTrack>> getAllTracks({required String dbPath}) =>
    RustLib.instance.api.crateApiDatabaseGetAllTracks(dbPath: dbPath);

Future<void> saveLearningRule(
        {required String dbPath, required LearningRule rule}) =>
    RustLib.instance.api
        .crateApiDatabaseSaveLearningRule(dbPath: dbPath, rule: rule);

Future<List<LearningRule>> getLearningRules({required String dbPath}) =>
    RustLib.instance.api.crateApiDatabaseGetLearningRules(dbPath: dbPath);

class DbTrack {
  final String id;
  final String title;
  final String artist;
  final String? album;
  final String localPath;

  const DbTrack({
    required this.id,
    required this.title,
    required this.artist,
    this.album,
    required this.localPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      localPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbTrack &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          localPath == other.localPath;
}

class LearningRule {
  final String? artist;
  final String field;
  final String originalValue;
  final String correctedValue;

  const LearningRule({
    this.artist,
    required this.field,
    required this.originalValue,
    required this.correctedValue,
  });

  @override
  int get hashCode =>
      artist.hashCode ^
      field.hashCode ^
      originalValue.hashCode ^
      correctedValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LearningRule &&
          runtimeType == other.runtimeType &&
          artist == other.artist &&
          field == other.field &&
          originalValue == other.originalValue &&
          correctedValue == other.correctedValue;
}
