// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Gera uma "Assinatura Acústica" simplificada baseada nos primeiros segundos do áudio real.
/// Isso permite detectar se dois arquivos são a mesma música mesmo que tenham formatos diferentes.
Future<String> generateAcousticFingerprint({required String path}) =>
    RustLib.instance.api
        .crateApiDuplicatesGenerateAcousticFingerprint(path: path);

/// Diagnostica a integridade de um arquivo de áudio.
Future<String> diagnoseFile({required String path}) =>
    RustLib.instance.api.crateApiDuplicatesDiagnoseFile(path: path);

/// Tenta reparar o cabeçalho (header) de um arquivo usando Lofty.
Future<String> repairFileHeader({required String path}) =>
    RustLib.instance.api.crateApiDuplicatesRepairFileHeader(path: path);
