// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Gera uma "impressão digital" (fingerprint) básica extraindo e hasheando
/// as amostras de áudio brutas dos primeiros 10 segundos da música.
/// Isso permite identificar arquivos idênticos no som, mesmo que tenham metadados ou nomes diferentes.
Future<AcousticFingerprint> generateFingerprint({required String path}) =>
    RustLib.instance.api.crateApiFingerprintGenerateFingerprint(path: path);

class AcousticFingerprint {
  final String hash;
  final double durationSeconds;

  const AcousticFingerprint({
    required this.hash,
    required this.durationSeconds,
  });

  @override
  int get hashCode => hash.hashCode ^ durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcousticFingerprint &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          durationSeconds == other.durationSeconds;
}
