// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Busca a letra de uma música usando uma API pública.
Future<String> searchLyrics({required String artist, required String title}) =>
    RustLib.instance.api
        .crateApiLyricsSearchLyrics(artist: artist, title: title);

/// Grava a letra permanentemente no arquivo de áudio (Tag USLT/Lyrics).
Future<void> embedLyricsToFile(
        {required String path, required String lyrics}) =>
    RustLib.instance.api
        .crateApiLyricsEmbedLyricsToFile(path: path, lyrics: lyrics);
