// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<AudioMetadata> readMetadata({required String path}) =>
    RustLib.instance.api.crateApiMetadataReadMetadata(path: path);

Future<List<ResultAudioMetadataString>> readMetadataBatch(
        {required List<String> paths}) =>
    RustLib.instance.api.crateApiMetadataReadMetadataBatch(paths: paths);

Future<void> writeMetadata(
        {required String path, required AudioMetadata metadata}) =>
    RustLib.instance.api
        .crateApiMetadataWriteMetadata(path: path, metadata: metadata);

Future<Uint8List?> extractCoverArt({required String path}) =>
    RustLib.instance.api.crateApiMetadataExtractCoverArt(path: path);

Future<Uint8List?> extractAndOptimizeCover(
        {required String path, required int maxSize}) =>
    RustLib.instance.api
        .crateApiMetadataExtractAndOptimizeCover(path: path, maxSize: maxSize);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Result < AudioMetadata , String >>>
abstract class ResultAudioMetadataString implements RustOpaqueInterface {}

class AudioMetadata {
  final String? title;
  final String? artist;
  final String? album;
  final int? year;
  final int? trackNumber;
  final String? genre;
  final int durationMs;
  final String filePath;

  const AudioMetadata({
    this.title,
    this.artist,
    this.album,
    this.year,
    this.trackNumber,
    this.genre,
    required this.durationMs,
    required this.filePath,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      year.hashCode ^
      trackNumber.hashCode ^
      genre.hashCode ^
      durationMs.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          year == other.year &&
          trackNumber == other.trackNumber &&
          genre == other.genre &&
          durationMs == other.durationMs &&
          filePath == other.filePath;
}
