// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RenamePreview`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Gera um preview da renomeação e retorna como uma string JSON para o Dart.
Future<String> getRenamePreview(
        {required List<String> paths, required String rule}) =>
    RustLib.instance.api
        .crateApiRenamerGetRenamePreview(paths: paths, rule: rule);

/// Executa a renomeação real a partir de uma lista de previews em JSON.
Future<String> executeRenameBatch({required String jsonPreviews}) =>
    RustLib.instance.api
        .crateApiRenamerExecuteRenameBatch(jsonPreviews: jsonPreviews);
