// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Cria um snapshot (ponto de restauração) dos metadados de um arquivo.
Future<void> createMetadataSnapshot(
        {required String dbPath,
        required String filePath,
        required String metadataJson}) =>
    RustLib.instance.api.crateApiSnapshotsCreateMetadataSnapshot(
        dbPath: dbPath, filePath: filePath, metadataJson: metadataJson);

/// Recupera o histórico de versões de um arquivo.
Future<List<String>> getFileHistory(
        {required String dbPath, required String filePath}) =>
    RustLib.instance.api
        .crateApiSnapshotsGetFileHistory(dbPath: dbPath, filePath: filePath);
