// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sincroniza as tags de um arquivo "Mestre" para todos os outros arquivos que possuem o mesmo som.
Future<String> syncTagsAcrossFormats(
        {required String masterPath, required List<String> otherPaths}) =>
    RustLib.instance.api.crateApiSyncSyncTagsAcrossFormats(
        masterPath: masterPath, otherPaths: otherPaths);
