// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Retorna informações detalhadas sobre o codec e formato de um arquivo de áudio.
Future<String> getAudioDetails({required String path}) =>
    RustLib.instance.api.crateApiTranscodeGetAudioDetails(path: path);

/// Motor de Transcoding Real: Decodifica um arquivo e prepara para escrita.
Future<String> convertToWav(
        {required String inputPath, required String outputPath}) =>
    RustLib.instance.api.crateApiTranscodeConvertToWav(
        inputPath: inputPath, outputPath: outputPath);
