// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Registra o aplicativo no menu de contexto do Windows Explorer (Botão Direito).
Future<String> registerShellExtension({required String exePath}) =>
    RustLib.instance.api
        .crateApiWindowsShellRegisterShellExtension(exePath: exePath);

/// Remove a integração com o Shell.
Future<String> unregisterShellExtension() =>
    RustLib.instance.api.crateApiWindowsShellUnregisterShellExtension();
