// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Lista os dispositivos móveis vinculados.
Future<List<String>> listConnectedMobileDevices() =>
    RustLib.instance.api.crateApiWindowsDevicesListConnectedMobileDevices();

/// SISTEMA FINALIZADO: Realiza o "Turbo Push" do arquivo para o dispositivo móvel.
Future<String> pushToMobileDevice(
        {required String localPath, required String deviceName}) =>
    RustLib.instance.api.crateApiWindowsDevicesPushToMobileDevice(
        localPath: localPath, deviceName: deviceName);

/// Função de utilidade para abrir a pasta do celular no Explorer via Rust.
Future<void> openMobileFolderInExplorer({required String deviceName}) => RustLib
    .instance.api
    .crateApiWindowsDevicesOpenMobileFolderInExplorer(deviceName: deviceName);
