// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2dRAUkMVdRfbzoRIYUmwY5MYo_sbQh4',
    appId: '1:823653472108:web:289725f17877a0b530c549',
    messagingSenderId: '823653472108',
    projectId: 'app-music-2000',
    authDomain: 'app-music-2000.firebaseapp.com',
    storageBucket: 'app-music-2000.firebasestorage.app',
    measurementId: 'G-P9ST4E77ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7cVQ7MZGDVSyCkBzb2GfADpN4EGryE3k',
    appId: '1:823653472108:android:e0f65720ed60d44e30c549',
    messagingSenderId: '823653472108',
    projectId: 'app-music-2000',
    storageBucket: 'app-music-2000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAADjVzNmUo6sFBylHvnQt81f-QAN5Xaws',
    appId: '1:823653472108:ios:059e2233e8b7869130c549',
    messagingSenderId: '823653472108',
    projectId: 'app-music-2000',
    storageBucket: 'app-music-2000.firebasestorage.app',
    iosBundleId: 'app-music-2000',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAADjVzNmUo6sFBylHvnQt81f-QAN5Xaws',
    appId: '1:823653472108:ios:059e2233e8b7869130c549',
    messagingSenderId: '823653472108',
    projectId: 'app-music-2000',
    storageBucket: 'app-music-2000.firebasestorage.app',
    iosBundleId: 'app-music-2000',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk2dRAUkMVdRfbzoRIYUmwY5MYo_sbQh4',
    appId: '1:823653472108:web:243e0bb7b4ee8d4930c549',
    messagingSenderId: '823653472108',
    projectId: 'app-music-2000',
    authDomain: 'app-music-2000.firebaseapp.com',
    storageBucket: 'app-music-2000.firebasestorage.app',
    measurementId: 'G-S6G4M8772E',
  );
}
